import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Clock, Instagram, MapPin, MessageCircle, Navigation, Tag } from "lucide-react";
import casaImg from "@/assets/casa-porto.jpg";
import brasaImg from "@/assets/brasa-83.jpg";
import cafeImg from "@/assets/cafe-aurora.jpg";
import { AppBadge, BusinessCard, SectionTitle } from "@/components/platform";
import { Button } from "@/components/ui/button";
import { businesses } from "@/lib/mock-data";

export const Route = createFileRoute("/negocio/restaurante-exemplo")({ head: () => ({ meta: [
  { title: "Casa do Porto — Restaurante em Tambaú" }, { name: "description", content: "Conheça a página demonstrativa da Casa do Porto, restaurante fictício em Tambaú, João Pessoa." },
  { property: "og:title", content: "Casa do Porto — Melhores Jampa" }, { property: "og:description", content: "Perfil demonstrativo de um restaurante fictício em Tambaú." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: BusinessPage });

function BusinessPage() {
  const [notice, setNotice] = useState("");
  return <><section className="relative min-h-[72svh] overflow-hidden bg-primary text-primary-foreground"><img src={casaImg} alt="Ambiente ilustrativo da Casa do Porto" width={1600} height={1072} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-primary via-primary/25 to-transparent" /><div className="shell relative flex min-h-[72svh] items-end pb-12"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><AppBadge type="Em destaque" /><AppBadge type="Premiado 2025" /></div><h1 className="mt-5 text-5xl font-bold sm:text-7xl">Casa do Porto</h1><p className="mt-3 flex items-center gap-2 text-lg text-primary-foreground/80"><span>Restaurante</span><span>•</span><MapPin className="size-5" /> Tambaú, João Pessoa</p></div></div></section>
  <section className="sticky top-16 z-30 border-b border-border bg-background/95 py-3 backdrop-blur"><div className="shell flex gap-2 overflow-x-auto">{[[Instagram,"Instagram"],[MessageCircle,"WhatsApp"],[Navigation,"Como chegar"]].map(([Icon,label]) => <Button key={label as string} variant="outline" onClick={() => setNotice(`${label} é uma ação ilustrativa neste protótipo.`)}><Icon />{label as string}</Button>)}</div></section>
  {notice && <div className="shell pt-5"><div role="status" className="rounded-md bg-secondary px-4 py-3 text-sm">{notice}</div></div>}
  <section className="section-space"><div className="shell grid gap-12 lg:grid-cols-[minmax(0,1.4fr)_minmax(280px,.6fr)]"><div><SectionTitle eyebrow="Sobre" title="Sabores que encontram o mar" /><p className="max-w-3xl text-lg leading-relaxed text-muted-foreground">A Casa do Porto é um restaurante fictício criado para demonstrar como um negócio pode apresentar sua atmosfera, proposta e informações essenciais dentro da plataforma. Uma cozinha contemporânea inspirada no litoral paraibano, em um ambiente acolhedor para encontros especiais.</p><div className="mt-8 grid grid-cols-2 gap-3"><img src={brasaImg} alt="Prato ilustrativo" loading="lazy" width={1408} height={1056} className="aspect-square w-full rounded-lg object-cover" /><img src={cafeImg} alt="Ambiente ilustrativo" loading="lazy" width={1408} height={1056} className="aspect-square w-full rounded-lg object-cover" /></div></div><aside className="h-fit rounded-lg border border-border bg-card p-6 shadow-sm"><h2 className="text-2xl font-bold">Informações</h2><dl className="mt-6 grid gap-5">{[[MapPin,"Endereço","Av. Exemplo, 123 · Tambaú"],[Clock,"Horário","Ter–Dom · 12h às 23h"],[Tag,"Categoria","Restaurante · $$$"]].map(([Icon,title,copy]) => <div key={title as string} className="grid grid-cols-[auto_1fr] gap-3"><Icon className="mt-1 size-5 text-sea"/><div><dt className="font-bold">{title as string}</dt><dd className="mt-1 text-sm text-muted-foreground">{copy as string}</dd></div></div>)}</dl></aside></div></section>
  <section className="bg-secondary py-12"><div className="shell"><SectionTitle eyebrow="Reconhecimentos" title="Uma história de destaque" /><div className="max-w-xl rounded-lg bg-card p-6 shadow-sm"><AppBadge type="Melhores do Ano 2025" /><h3 className="mt-4 text-2xl font-bold">Reconhecimento demonstrativo</h3><p className="mt-2 text-sm text-muted-foreground">Premiação fictícia, independente da presença comercial atual.</p></div></div></section>
  <section className="section-space"><div className="shell"><SectionTitle eyebrow="Continue explorando" title="Também pode interessar" /><div className="grid gap-5 sm:grid-cols-3">{businesses.slice(1,4).map(b => <BusinessCard key={b.name} business={b} compact />)}</div></div></section></>;
}